import {
    Globe,
    Lock,
    Coins,
    Skull,
    Terminal,
    ChevronsRight,
    Binary,
    Server,
    AlertTriangle,
    FileWarning,
    Cpu,
    UserX,
    Eye,
} from "lucide-svelte";

// Placeholder for icon if missing
const BuildingBank = Server;

export const slides = [
    {
        id: "intro",
        title: "PROJECT: LAZARUS",
        subtitle: "De Usurpator van de Digitale Wereld",
        type: "title",
    },
    {
        id: "origin",
        title: "Bureau 121",
        subtitle: "De Oorsprong",
        content: [
            "Locatie: Pyongyang, Noord-Korea (en China)",
            "Elite hackers geselecteerd uit wiskunde-talenten",
            "Start training op jonge leeftijd (middelbare school)",
            "Onderdeel van de 'Reconnaissance General Bureau'",
        ],
        icon: Globe,
        accent: "text-blue-400",
        type: "content",
    },
    {
        id: "motive",
        title: "De Missie",
        subtitle: "Waarom hackt een staat?",
        content: [
            "1. Financieel gewin (Sancties omzeilen)",
            "2. Spionage (Technologie & Geheimen)",
            "3. Destabilisatie (Chaos creëren)",
            "Geschatte opbrengst: $3 Miljard+ voor het kernwapenprogramma",
        ],
        icon: Coins,
        accent: "text-green-400",
        type: "content",
    },
    {
        id: "sony_deep",
        title: "Case: Sony Pictures",
        subtitle: "2014 - De Eerste Cyberoorlog Daad?",
        content: [
            "Aanleiding: De film 'The Interview'",
            "Aanval: Wisper-malware wiste harde schijven",
            "Diefstal: Onuitgebrachte films, e-mails, salarisstroken",
            "Gevolg: Obama legde sancties op, Sony trok film terug",
        ],
        icon: Skull,
        accent: "text-red-500",
        type: "content",
    },
    {
        id: "simulation",
        title: "INTERACTIEVE SIMULATIE",
        subtitle: "Druk op [SPATIE] om de firewall te doorbreken...",
        type: "hack",
        accent: "text-yellow-400",
    },
    {
        id: "bangladesh_deep",
        title: "Case: De Bankroof",
        subtitle: "Bangladesh Bank Heist (2016)",
        content: [
            "Doelwit: Federal Reserve Bank of New York",
            "Methode: Gecompromitteerde SWIFT-credentials",
            "Bijna gelukt: $1 Miljard in transfers",
            "De fout: Hackers typten 'Fandation' i.p.v. 'Foundation'",
            "Buit: 'Slechts' $81 Miljoen",
        ],
        icon: BuildingBank, 
        accent: "text-orange-400",
        type: "content",
    },
    {
        id: "wannacry_deep",
        title: "Case: WannaCry",
        subtitle: "Mei 2017 - Ransomware",
        content: [
            "Wapen: 'EternalBlue' (Gestolen van NSA)",
            "Slachtoffers: NHS (UK), FedEx, Telefonica",
            "Schade: 200,000+ computers versleuteld",
            "De 'Kill Switch': Ontdekt door Marcus Hutchins",
        ],
        icon: Lock,
        accent: "text-purple-500",
        type: "content",
    },
    {
        id: "modern",
        title: "Moderne Tactieken",
        subtitle: "Social Engineering 2.0",
        content: [
            "Doelwit: Crypto & DeFi ontwikkelaars",
            "Methode: Nep recruiters op LinkedIn",
            "De Val: 'Hier is een geweldige baan... open deze PDF'",
            "Resultaat: Axie Infinity Hack ($625M)",
        ],
        icon: UserX,
        accent: "text-cyan-400",
        type: "content",
    },
    {
        id: "outro",
        title: "Systeem Gecompromitteerd",
        content: [
            "De dreiging is permanent.",
            "Ze zijn geduldig.",
            "Ze zijn overal.",
        ],
        type: "title",
    },
];
